# Generated by Django 2.2.5 on 2019-10-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='haha'),
            preserve_default=False,
        ),
    ]
