# Generated by Django 2.2.5 on 2019-10-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_time']},
        ),
    ]
