# Generated by Django 2.2.5 on 2019-10-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xfzauth', '0002_auto_20191010_1014'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
